# Generated by Django 6.0.4 on 2026-04-08 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telegramuser',
            old_name='firs_name',
            new_name='first_name',
        ),
    ]
